### ISSUE TITLE
Not receiving marketing fees

### ISSUE THREAD

**Issue by Gaex99** [SwapOcean/token#1]
I created my contract and I launched it, but i'm not receiving anything from marketing having 7% of taxes, how can it be fixed? This is my contract 0xb1089b8b63a4911546d37b560b060eba7d52ef9e

**Comment by SwapOceanProject** [comment]
You have to create liquidity pool on https://bsc.swapocean.com/

**Comment by Gaex99** [comment]
Also the taxes are setted wrong in the code, when I increase the tax fees for reflections the buy tax is higher than the sell tax, i will migrate my holders to a new contract, vote 0/10.
